### ISSUE TITLE
network.rnnTimeStep() throws cudaStreamSynchronize(...) failed, when timeStep is very long.

### ISSUE THREAD

**Issue by cqiaoYc** [eclipse/deeplearning4j#7891]
#### Issue Description

Please describe our issue, along with:
timeStep=5990, and batchSize=48;
network.rnnTimeStep() throws an exception:
CUDA error at /mnt/jenkins/workspace/deeplearning4j-deeplearning4j-1.0.0-beta4-linux-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:1903 code=77(<unknown>) "dZ" 
CUDA error at /mnt/jenkins/workspace/deeplearning4j-deeplearning4j-1.0.0-beta4-linux-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:1903 code=77(<unknown>) "dZ" 
CUDA error at /mnt/jenkins/workspace/deeplearning4j-deeplearning4j-1.0.0-beta4-linux-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:1903 code=77(<unknown>) "dZ" 
CUDA error at /mnt/jenkins/workspace/deeplearning4j-deeplearning4j-1.0.0-beta4-linux-x86_64-cuda-10.0/libnd4j/blas/cuda/NativeOps.cu:1903 code=77(<unknown>) "dZ" 
Exception in thread "pool-1-thread-1" Exception in thread "pool-1-thread-2" java.lang.RuntimeException: cudaStreamSynchronize(...) failed
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
	at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:131)
	at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:121)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.commit(CudaExecutioner.java:1866)
	at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:602)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1309)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3065)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3046)
.....
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: cudaStreamSynchronize(...) failed
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize(Native Method)
	at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:131)
	at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:121)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.commit(CudaExecutioner.java:1866)
	at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:602)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.outputOfLayerDetached(MultiLayerNetwork.java:1309)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3065)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.rnnTimeStep(MultiLayerNetwork.java:3046)
......
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 1.0-beta4
* platform information (OS, etc): ubuntu18.04
* CUDA version, 10.0
* NVIDIA driver version, 7.4

GPU: GXT1080

**Comment by cqiaoYc** [comment]
when batchSize=32, it can work.

**Comment by JSpiegel** [comment]
That looks quite similar to my issue #7795

**Comment by raver119** [comment]
@cqiaoYc do you have cuDNN installed/enabled?

**Comment by cqiaoYc** [comment]
@raver119 cuDNN is OK. I guessed the problem was caused by memory overrun.
